
services:
  backend:
  
    build: 
    
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_DB_URI=mongodb+srv://gautamashastry:gautam20@cluster0.avl6e.mongodb.net/task-manager-db?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=5QuOLvOubj5XUzWYlgUPLQnVeCeOW9VL17Ct4waBsHM=
      - NODE_ENV="production"